name: Server Release

on:
  push:
    tags: [v*.*.*]
    paths:
      - "server/**"

jobs:
  publish:
    name: Publish server docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: docker_meta
        name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: agnjunio/albion-killbot
          tags: type=semver,pattern={{version}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Server
        uses: docker/build-push-action@v3
        with:
          context: server/
          file: server/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy-crawler:
    name: Deploy crawler
    runs-on: ubuntu-latest
    needs:
      - publish
    environment: production
    steps:
      - name: Deploy crawler
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ vars.SSH_HOST_CRAWLER }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose --ansi never up -d --pull always --force-recreate

  deploy-bot:
    name: Deploy bot shards
    runs-on: ubuntu-latest
    needs:
      - publish
    environment: production
    strategy:
      matrix:
        shard: [0, 1]
        include:
        - shard: 0
          SSH_HOST: SSH_HOST_0
        - shard: 1
          SSH_HOST: SSH_HOST_1
    steps:
      - name: Deploy bot shard '#${{ matrix.shard }}'
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets[matrix.SSH_HOST] }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose --ansi never pull
            docker compose --ansi never down
            if [[ ${{ matrix.shard }} == 0 ]]; then touch migration-state.json; docker compose --ansi never run --rm bot npm run db:migrate; fi
            docker compose --ansi never up -d

  deploy-api:
    name: Deploy api
    runs-on: ubuntu-latest
    needs:
      - publish
    environment: production
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy api
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: agnjunio/albion-killbot:latest
          service: api
    
